name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem/Need
      description: What problem does this solve?
      placeholder: Describe the problem or need...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: Describe your solution...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - UI/UX
        - Performance
        - Content
        - Functionality
        - Accessibility
        - SEO
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      placeholder: Mockups, examples, references...
