name: 📋 Task/TODO
description: Track development tasks
title: "[Task]: "
labels: ["task"]

body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: What needs to be done?
      placeholder: Describe the task...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Development
        - Design
        - Content
        - Testing
        - Documentation
        - DevOps/CI
        - Security
        - Performance
        - SEO
        - Maintenance
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: Implementation notes, dependencies, etc.